### ISSUE TITLE
Provide advice for `tibble::tribble()` calls

### ISSUE THREAD

**Issue by etiennebacher** [posit-dev/air#102]
Hello, thank you for this tool! After using Ruff and rustfmt, I'm very happy to see fast formatting coming to R.

I was testing `air` on some packages and noticed that `tibble::tribble()` are reformatted with one element per line, which makes it harder to read:

**Before**:
```r
tribble(
  ~colA, ~colB,
  "a",   1,
  "b",   2,
  "c",   3
)
```
**After**:
```r
tribble(
  ~colA,
  ~colB,
  "a",
  1,
  "b",
  2,
  "c",
  3
)
```
I saw this was mentioned in #26 but the issue is now closed and I didn't find any mention of this in `docs/formatter.md`, so I'm just opening this so that it is tracked somewhere. I hope it's not a duplicate.

Thanks again

---

Tested on `main` with [093bb96](https://github.com/posit-dev/air/commit/093bb96d41e948979d193ae6c23e3872978c6a26)

**Comment by DavisVaughan** [comment]
Yes, right now there is no way to avoid the mess that you see here with `tribble()` calls.

We _really_ want to avoid hardcoding any specific function names into the formatter. One idea is to turn off formatting altogether. You can't do this yet but it would look something like

```r
# air format: ignore
tribble(
  ~x,   ~y
  1,    2
)
```

We are also considering more powerful comments that would actually _help_ you enforce a particular format, like

```r
# air format: layout-tabular
tribble(
  ~x,   ~y
  1,    2
)
```

This would snap you into a rectangular layout as you type to help you out (probably falling back to a "verbatim" what-you-see-is-what-you-get layout if the number of arguments doesn't divide evenly into a rectangle)

**Comment by lionel-** [comment]
Closing in favour of: https://github.com/posit-dev/air/issues/113
