### ISSUE TITLE
`%||%` followed by `|>` puts all pipes on the same line

### ISSUE THREAD

**Issue by etiennebacher** [posit-dev/air#104]
This example:
```r
a <- "foo"
a %||% "bar" |>
  paste("baz") |>
  paste("baz2")

```
is reformatted to:
```r
a <- "foo"
a %||% "bar" |> paste("baz") |> paste("baz2")
```
I suppose this is a precedence issue since the following isn't modified:
```r
a <- "foo"
(a %||% "bar") |>
	paste("baz") |>
	paste("baz2")
```
However, the original code (without parenthesis) correctly returns `"foo baz baz2"` and therefore shouldn't be reformatted.

**Comment by etiennebacher** [comment]
Actually maybe it is weird that `a %||% "bar" |> paste("baz") |> paste("baz2")` returns `"foo baz baz2"`. It seems that `%||%` has a different precedence from `+` for instance since this fails:

```r
1 + 1 |>
  paste("baz") |>
  paste("baz2")

Error in `1 + paste(paste(1, "baz"), "baz2")`:
! non-numeric argument to binary operator
```

I don't know enough on this topic, I'll let you determine if this is a precedence bug or not.

**Comment by lionel-** [comment]
The formatter respects newlines in pipelines after the _first_ operand. Since there is no newline after `%||%`, it considers the flat display by default (if it fits).

You can either add a newline after `%||%`:

```r
a %||%
  "bar" |> paste("baz") |>
  paste("baz2")

# Formats as
a %||%
  "bar" |>
  paste("baz") |>
  paste("baz2")
```

Or add parentheses:

```r
(a %||% "bar") |>
  paste("baz") |>
  paste("baz2")
```

Or even better:

```r
a <- a %||% "bar"

a |>
  paste("baz") |>
  paste("baz2")
```
