### ISSUE TITLE
Consider enforcing line breaks for pipe chains of >=2 pipes

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/air#28]
```r
# Input
x %>% fn()

# Expected output
x %>% fn()
```

```r
# Input
x %>% fn() %>% fn2()

# Expected output
x %>% 
  fn() %>% 
  fn2()
```

In the 2nd case, even though it fits on one line, I'd argue that once you do >1 thing in a pipe chain it should be forcibly split over multiple lines?

---

It's also possible that we could use this rule in place of "respect the user's line break" for pipes. The user would not be able to put single pipe chains across multiple lines if it fits, but that's probably ok?

**Comment by philibe** [comment]
Just a thought about my habits and the paragraph seen in the document you linked in another issue:

- https://peps.python.org/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

Without parenthesis it's obvious and mandatory in R to have the pipe at the end of the line, no problem :) Else there is an error:
```
x %>% 
fn1() 
%>% 
fn2()
%>%
 fn3()
```

But with parenthesis I have all my lines with pipe at the beginning of the line, subjectively more readable, specially for `mutate` :

```
( x 
  %>% fn1() 
  %>% fn2()
  %>% fn3()
)
```

But I can understand that is simpler in R to not take risk to have an error, and have the pipe at the end of the line

**Comment by lionel-** [comment]
Right we generally favour formatting that works regardless of context so that copy-pasting is easy.
