### ISSUE TITLE
Apply magic line breaks in left assignment operators

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/air#91]
I often prefer to have the function call, if/else block, or `%||%` chain on a new line in an assignment:

```r
is_condition_true <- 
  if (condition) {
    "yes"
  } else {
    "no"
  }

base_version <- 
  version %||%
  b_get(brand, "defaults", "shiny", "theme", "version") %||%
  b_get(brand, "defaults", "bootstrap", "version") %||%
  version_default()
```

Would you consider applying the magic line break logic to the first operator? In other words, the presence of the line break after `<-` would trigger the above formatting.

**Comment by DavisVaughan** [comment]
Yea `<-` is one of the places we plan to add this. It is mentioned here if you havent seen this draft doc yet (but isn't implemented yet) https://github.com/posit-dev/air/blob/main/docs/formatter.md#left-assignment
